### ISSUE TITLE
Observations and Research Variables

### ISSUE THREAD

**Issue by ehsanmaag** [jpcik/medred#14]
Hello,

I am using MedRed ontology to create instances of PHQ9 questionnaires along with imaginary patient answers. In MedRed there is a Variable class that allows definition of research variables. However it is not clear to me: How observations (questions' answers) are connected with the specified output variable for a specific question?

Any help is greatly appreciated!

**Comment by jpcik** [comment]
Hi,

Question answers are Record instances in medred. Each record has a valueList, which is an ordered list of values (the answers to the questions)
Each record also has varNameList, which is the list of variable names. This name matches the varName field of the Variable in the questionnaire.

Perhaps there could be a way of creation a more detailed version of each answer, linking each one to its corresponding variable, but for now this is how it is linked.

**Comment by ehsanmaag** [comment]
Thank you for the explanation @jpcik
